### ISSUE TITLE
Error in folder where extension is disabled

### ISSUE THREAD

**Issue by jeffchasin** [AdobeDocs/vsc-extensions#20] opened 2021-11-24 17:53 UTC
Seeing: `ERROR: Exception while linting with markdownlint-cli2: Error: Cannot find module '{adobeexl.adobe-markdown-authoring}/markdownlint-custom-rules/rules.js'` in a folder where Adobe Markdown Authoring is disabled. If the extension is disabled globally, not sure why those custom rules are still running?

![AdobeMdAuth-disabled](https://user-images.githubusercontent.com/3515173/143289868-f7690085-1b0b-4087-9f46-539de6830499.png)

I installed the extension from the [marketplace](https://marketplace.visualstudio.com/items?itemName=AdobeExL.adobe-markdown-authoring) then disabled it globally. I have it enabled only in the workspace where I do AdobeDocs work. I would expect the markdownlint-custom-rules to only run in that workspace where the extension is enabled. Not sure what's happening under the hood here tho. Anyone?

**Comment by geverit4** [comment] 2021-11-30 02:10
Sorry for the delayed response.  I am able to reproduce this problem and am working to address it.

**Comment by jeffchasin** [comment] 2021-11-30 02:15
Thanks! 🙏

**Comment by geverit4** [comment] 2021-11-30 02:45
I'm working on automating this in the Adobe Markdown Authoring uninstall script, but in the mean time, you can manually edit your settings to eliminate this error message. 

In Visual Studio Code (for Mac)
- Open your User Settings  Code-> Preferences -> Settings (Cmd-,)
- Under Extensions->markdownllint find Markdownlint: Custom Rules, remove the _{adobeexl.adobe-markdown-authoring}/markdownlint-customer-rules/rules.js_ entry by clicking on the trash can next to the entry

If you want, restart Code to clear the output error message.   Or, you can use the "Clear Output" option under the markdownlint extension Output panel that displays the error message.   

When the Adobe Markdown Authoring Extension is loaded, it automatically adds the Custom Rules entry to your user settings, but unfortunately, it does not undo that when uninstalling the extension.  I'm working on fixing that.

**Comment by jeffchasin** [comment] 2021-11-30 02:57
Thanks! Would really be cool to have the option to apply the Custom Rules entry to either Workspace, or User settings, and eventually, undo on Uninstall.  Regardless of that, I didn't `Uninstall` the extension, I _disabled_ it globally, then _enabled_ it in a workspace. This makes the extension _Enabled_ only in the workspace where I do AdobeDocs work, but _Disabled_ everywhere else. Not sure how Disabling or Enabling only _in a Workspace_ impacts those settings at the User level tho?

**Comment by geverit4** [comment] 2022-01-10 22:26
This is a duplicate of Issue #5.  It has been fixed.

**Closed by geverit4** 2022-01-10 22:26 UTC
